services:
  kafka:
    image: bitnamilegacy/kafka:4.0
    container_name: kafka
    ports:
      - "9092:9092" # 호스트에서 접근
      - "29092:29092" # 내부 컨테이너 네트워크용
    environment:
      # KRaft 모드 설정
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

      # 단일 브로커 클러스터 ID (고정값 가능)
      - KAFKA_KRAFT_CLUSTER_ID=MielseielG12lu1ewn1192yA

      # 개발 환경이므로 인증 없이 허용
      - ALLOW_PLAINTEXT_LISTENER=yes
  redis:
    image: redis:8.2.1
    container_name: redis
    ports:
      - "6379:6379"
