name: ML Daily Jobs

on:
  schedule:
    - cron: "0 4 * * *" # 매일 UTC 04:00 → KST 13:00
  workflow_dispatch: # 수동 실행도 가능하게 함

jobs:
  run-ml-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run collector.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          ECOS_API_KEY: ${{ secrets.ECOS_API_KEY }}
        run: python -m ml.collector
        working-directory: ./backend

      - name: Run predictor.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
        run: python -m ml.predictor
        working-directory: ./backend
